---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/kkagucom/public_html/talentpoolacademy/
    - /bin/rsync -av --exclude='admin/includes/config.php' . $DEPLOYPATH
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;
